name: CI
on: [push, pull_request]

env:
  TERM: 'xterm'

jobs:
  unit-tests:
    strategy:
      matrix:
        editor: ['vim', 'neovim']
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.editor == 'neovim' }}
      - name: Run syntax tests
        working-directory: test
        run: |
          ${{ steps.vim.outputs.executable }} -u vimrc -U NONE -i NONE -n -N -e -s -c 'Vader! syntax.vader tsx.vader'
